---
- name: Load OS specific variables
  include_vars: '{{ ansible_distribution }}.yml'
  tags:
    - always

- block:

    - name: Install requirements
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ pulp_preq_packages }}"

    - name: Install Redis
      package:
        name: redis-server
        state: present

    - name: Start Redis
      systemd:
        name: "{{ pulp_redis_server_name }}"
        state: started
        enabled: yes
        daemon_reload: yes

  become: true
